name: Sync Fork

on:
  schedule:
    - cron: '* 11 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v1.4
        with:
          owner: uploadcare
          base: main
          head: main
          merge_method: rebase
          auto_approve: false
          auto_merge: true
